### PR TITLE
add pecl yaml library, fixed composer hash

### PR DESCRIPTION
**Pull request by BasilSnowman**
#14 

Add pecl yaml library.
Fixed composer installer hash.

### CODE REVIEW

**Comment by andypost** [comment]
I'm sure better to file MR to alpine repo as pointed in #14

**Comment by BasilSnowman** [comment]
why alpine repo? we create containers for php. for internal needs.

**Comment by andypost** [comment]
Because it's easy to manage and install instead of building locally, also having this package in ALpine will bring more eyes and testers

PS Your approach more like https://github.com/anavarre/drucker/commit/2ce24beb0ed9e3a7478d5c9ad51fa17c48450b7c but it will take more time and makes image size bigger

**Comment by andriyun** [comment]
@BasilSnowman need update branch and resolve conflicts

**Comment by andypost** [comment]
Also there's core issue about compatibility, not solved yet

https://www.drupal.org/node/2792877

**Pull request closed without merging**
